### ISSUE TITLE
Init fuction not save data

### ISSUE THREAD

**Issue by tran-the-lam** [hyperledger/fabric-contract-api-go#106]
I have one smart-contract and init function to save data, but smc  was deployed then I get value from key, data return "".

```
type SmartContract struct {
	contractapi.Contract
}

type User struct {
	UserID   string `json:"user_id"`
	Role     string `json:"role"`
	Password string `json:"password"`
}

func (s *SmartContract) Init(ctx contractapi.TransactionContextInterface) error {

	// Create User With Admin Role
	admin := User{
		UserID:   "admin",
		Role:     "admin",
		Password: "7ebd1a9b3dc007e9a9393ab3bd2848c6425f9218a00181775d4d311af048d023",
	}

	adminJSON, err := json.Marshal(admin)
	if err != nil {
		return err
	}

	if err := ctx.GetStub().PutState(admin.UserID, adminJSON); err != nil {
		return fmt.Errorf("failed to put to world state. %s", err.Error())
	}

	return nil
}
```

```
/network.sh deployCC -ccn basic -ccp $PWD/smart-contract/chaincode -ccl go
```

Please help me!

**Comment by bestbeforetoday** [comment]
How did you invoke your Init transaction function after deploying the smart contract?

**Comment by bestbeforetoday** [comment]
Using Fabric v2 chaincode lifecycle deployment, the Init function is not called automatically. You can approve chaincode as requiring an initialization transaction function to be called before general use, but you need to invoke that initialization transaction function explicitly. See the [chaincode deployment documentation](https://hyperledger-fabric.readthedocs.io/en/release-2.5/chaincode_lifecycle.html) (particularly _Step Three: Approve a chaincode definition for your organization_) for more details.

 `Init` is a special function name required by the low-level chaincode API but has no special meaning when using the higher-level Contract API. You can use whatever transaction function name you want as an initialization function. You still need to invoke it explicitly.

It is generally recommended to embed initialization logic into your chaincode rather than require invocation of a special initialization function.

**Comment by tran-the-lam** [comment]
Thanks a lot
