### ISSUE TITLE
Unmaintained?

### ISSUE THREAD

**Issue by sebastianst** [hyperledger/fabric-contract-api-go#61]
The current Fabric release is [`2.4.2`](https://github.com/hyperledger/fabric/releases/tag/v2.4.2). This repo supports Farbric 2.1, so is lagging 3 minor versions behind. Also, the [latest release](https://github.com/hyperledger/fabric-contract-api-go/releases) was on 2020-10-21, so is over 1¼ years old.

Is this repo still maintained? Is anyone working on an update to support Fabric 2.4, or even future versions?

**Comment by jt-nti** [comment]
Hi @sebastianst, the repo is not tied to Fabric 2.1 specifically so it should work with more recent releases. We are currently trying to fix a test tool used by the CI pipeline so that we can hopefully get some updates in and a new release out soon. If you do hit any problems with Fabric 2.4, please open an issue. Thanks, James

**Comment by jt-nti** [comment]
Closing this issue after a long overdue v1.2.0 release
